Setup create invitations in DBManager and in Admin Dashboard
- invited guests still not working in Edit Event page
Weird SQL issue:

org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "﻿SELECT": syntax error)